{{- if eq .Values.clusterscope true }}
# NOTE: ClusterWorkflowTemplate "secret-resource" is a dependent of "create-secret-from-file".
# The filename of "secret-resource" is "0-secret.yaml", ensuring it is deployed first.
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: secret-resource
spec:
  activeDeadlineSeconds: 60
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  podGC:
    strategy: OnPodCompletion
  serviceAccountName: workflow

  templates:
    # Delete Secret resource
    - name: delete-secret-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: secretName
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.alias.input_secretName | quote }}
    # Create Secret resource with one key
    - name: create-secret-1key-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: secretName
          - name: key1
          - name: value1
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.alias.input_secretName | quote }}
          data:
            {{ .Values.alias.key1 | quote }}: {{ .Values.alias.value1 | quote }}
    # Create Secret resource with two key
    - name: create-secret-2key-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: secretName
          - name: key1
          - name: key2
          - name: value1
          - name: value2
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.alias.input_secretName | quote }}
          data:
            {{ .Values.alias.key1 | quote }}: {{ .Values.alias.value1 | quote }}
            {{ .Values.alias.key2 | quote }}: {{ .Values.alias.value2 | quote }}
{{- end }}
