{{- if eq .Values.clusterscope true }}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-secret-from-file
spec:
  activeDeadlineSeconds: 3600
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  podGC:
    strategy: OnPodCompletion
  serviceAccountName: workflow
  entrypoint: create-secret-from-file-tmpl

  templates:
    - name: create-secret-from-file-tmpl
      inputs:
        parameters:
          - name: secretName
          - name: filename
          - name: path
          - name: key
          - name: pvc_gupload
      steps:
        - - name: retrieve
            template: retrieve-tmpl
            arguments:
              parameters:
                - name: secretName
                  value: {{ .Values.alias.input_secretName | quote }}
                - name: filename
                  value: {{ .Values.alias.input_filename | quote }}
                - name: path
                  value: {{ .Values.alias.input_path | quote }}
                - name: key
                  value: {{ .Values.alias.input_key | quote }}
                - name: pvc_gupload
                  value: {{ .Values.alias.input_pvc_gupload | quote }}
        - - name: delete-secret-tmpl
            templateRef:
              name: secret-resource
              template: delete-secret-tmpl
              clusterScope: true
            arguments:
              parameters:
                - name: secretName
                  value: {{ .Values.alias.input_secretName  | quote }}
              continueOn:
                error: true
                failed: true
        - - name: create-secret-tmpl
            templateRef:
              name: secret-resource
              template: create-secret-1key-tmpl
              clusterScope: true
            arguments:
              parameters:
                - name: secretName
                  value: {{ .Values.alias.input_secretName | quote }}
                - name: key1
                  value: {{ .Values.alias.input_key | quote }}
                - name: value1
                  value: {{ .Values.alias.output_value1 | quote }}

    - name: retrieve-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      volumes:
        - name: gupload
          persistentVolumeClaim:
            claimName: {{ .Values.alias.input_pvc_gupload | quote }}
        - name: setup-script
          configMap:
            name: "orgadmin--setupsh"
            defaultMode: 0777
      inputs:
        parameters:
          - name: secretName
          - name: filename
          - name: key
          - name: path
          - name: pvc_gupload
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        workingDir: /
        args:
          - |-
            . /script/setup.sh
            FILE="{{ .Values.alias.input_path }}/{{ .Values.alias.input_filename }}"
            echo "Retrieving $FILE"
            if [ -f "$FILE" ]; then
              echo "file $FILE found"
              # NOTE: the cert is in base64 format, there is '\n' in each line. When it is passed via templateRef in
              # the "create-secret-tmpl" WorkflowTemplate, the passing parameter cannot process base64 properly.
              # it makes "\n" further escape; the break the base64 format. Here need to remove \n.
              set -x
              cat {{ .Values.alias.input_path }}/{{ .Values.alias.input_filename }} | tr -d '\r\n' > /tmp/{{ .Values.alias.input_filename }}
              res=$?
              set +x
              printMessage "{{ .Values.alias.input_filename }} found" $res
            else
              echo "file not found"
              exit 1
            fi
        volumeMounts:
          - mountPath: /var/gupload/fileserver
            name: gupload
          - name: setup-script
            mountPath: /script/setup.sh
            subPath: setup.sh
      outputs:
        parameters:
          - name: value1
            valueFrom:
              path:  "/tmp/{{ .Values.alias.input_filename }}"
{{- end }}
