{{- if eq .Values.clusterscope false }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gupload-dl-file
spec:
  activeDeadlineSeconds: 3600
  # podGC:
  #   strategy: OnPodCompletion
  serviceAccountName: workflow
  entrypoint: gupload-download-tmpl

  templates:
    # Retrieve file via gupload
    - name: gupload-download-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.alias.input_pvc_fabricfiles | quote }}
        - name: gupload
          persistentVolumeClaim:
            claimName: {{ .Values.alias.input_pvc_gupload | quote }}
        - name: setup-script
          configMap:
            name: "orgadmin--setupsh"
            defaultMode: 0777
      inputs:
        parameters:
          - name: url
          - name: filename
          - name: path
          - name: pvc_fabricfiles
          - name: pvc_gupload
      container:
        image: {{ .Values.guploadImage }}
        command: ["sh", "-c"]
        workingDir: /var/gupload/fileserver
        args:
          - |-
            . /script/setup.sh
            set -x
            ./gupload download --cacert {{ .Values.alias.input_filename }} --file {{ .Values.alias.input_filename }} --address {{ .Values.alias.input_url }}
            res=$?
            set +
            printMessage "gupload download" $res
        volumeMounts:
          - mountPath: /var/hyperledger
            name: fabricfiles
          - mountPath: /var/gupload/fileserver
            name: gupload
          - name: setup-script
            mountPath: /script/setup.sh
            subPath: setup.sh
{{- end }}
