{{- if eq .Values.clusterscope false }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: retrieve-http-file
spec:
  activeDeadlineSeconds: 3600
  # podGC:
  #   strategy: OnPodCompletion
  serviceAccountName: workflow
  entrypoint: retrieve-http-tmpl

  volumes:
    # binaries: peer, etc.
    - name: fabricfiles
      persistentVolumeClaim:
        claimName: {{ .Values.pvc_fabricfiles }}
    - name: gupload
      persistentVolumeClaim:
        claimName: {{ .Values.pvc_gupload }}
    - name: setup-script
      configMap:
        name: "orgadmin--setupsh"
        defaultMode: 0777

  templates:
    # Retrieve file via http
    - name: retrieve-http-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: url
          - name: filename
          - name: path
        artifacts:
          - name: file
            path: /tmp/{{ .Values.alias.input_filename }}
            http:
              url: {{ .Values.alias.input_url | quote }}
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        workingDir: /
        args:
          - |-
            . /script/setup.sh
            if [ -f "/tmp/{{ .Values.alias.input_filename }}" ]; then
              echo "file {{ .Values.alias.input_filename }} downloaded"
              ls -ls /tmp/{{ .Values.alias.input_filename }}
              cp /tmp/{{ .Values.alias.input_filename }} {{ .Values.alias.input_path }}/{{ .Values.alias.input_filename }}
              printMessage "{{ .Values.alias.input_path }}/{{ .Values.alias.input_filename }} created" $?
            else
              echo "file not found"
              exit 1
            fi
        volumeMounts:
          - mountPath: /var/hyperledger
            name: fabricfiles
          - mountPath: /var/gupload/fileserver
            name: gupload
          - name: setup-script
            mountPath: /script/setup.sh
            subPath: setup.sh
    # Delete Secret resource
    - name: delete-secret-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: secretName
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Values.alias.input_secretName | quote }}
  {{- end }}
