global:
  ### Default
  # TZ: Asia/Hong_Kong
  ### Default
  # workingDir: /var/hyperledger/crypto-config
  ### Default
  # logging: info
  mspId: Org1MSP
  caName: rca1

### Default
#image:
#  repository: hyperledger/fabric-ca
#  tag: 1.4.7
#  pullPolicy: IfNotPresent

### Default
service:
  ## NodePort or LoadBalancer (cannot ClusterIP)
  type: NodePort
  port: 7054

config:
  type: ca
  ### Default
  # debug: false
  csr:
    names:
      c: US
      st: "North Carolina"
      o: Hyperledger
      ou: Fabric
  affiliations: {}
  ## "intermediate" is only specified for Intermediate CA's
  # intermediate:
  #   parent:
  #     chart: parent-ca
  #     url: parent-ca.example.com
  #     port: 7054
  ## Affiliations used in ca Server configuration file

persistence:
  ### Default
  # enabled: true
  existingClaim: pvc-org1

externalDatabase:
  type: postgres
  # [Release Name]-postgresql-0
  host: admin1-postgresql-0
  port: 5432
  database: rca_db

### Default
#db:
#  ssl: disable
