global:
  logging: info

image:
  repository: ghcr.io/rtang03/ui-control-org1
  tag: 0.7.1
  pullPolicy: IfNotPresent

config:
  waitForAuthServer: auth-server1:8080
  authServerUri: http://auth-server1:8080
  gwOrgExternalHost: http://localhost:4001/graphql
  queryHandlerExternalHost: http://localhost:5001/graphql

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
