apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ord.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7050
      protocol: TCP
      name: tls-request
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ include "hlf-ord.name" . }}
    release: {{ .Release.Name }}
