apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: aoa-sync-org1-2
spec:
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      steps:
        - - name: sync-p0o1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "p0o1"
          - name: sync-g1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "g1"
        - - name: dl-create-tlscacert
            templateRef:
              name: download-and-create-secret
              template: main
            arguments:
              parameters:
                - name: filename
                  value: "org0.com-tlscacert.pem"
                - name: key
                  value: "tlscacert.pem"
                - name: path
                  value: /var/gupload/fileserver/public
                - name: pvc_gupload
                  value: "pvc-gupload1"
                - name: secretName
                  value: "org0.com-tlscacert"
                - name: url
                  value: "https://storage.googleapis.com/fabric-cd-dev/workflow/secrets/n0/org0.com-tlscacert/tlscacert.pem"
