apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: aoa-sync-gw-org1
spec:
  activeDeadlineSeconds: 900
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterSuccess: 3600
    secondsAfterFailure: 3600
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      steps:
        - - name: sync-redis1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "redis1"
        - - name: sync-auth1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "auth-server1"
        - - name: sync-gw-org1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "gw-org1"
        - - name: sync-ui-org1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "ui-org1"
