apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wow-bootstrap-org1-2
spec:
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      steps:
        - - name: sync-o0
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "o0"
          - name: sync-o1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "o1"
          - name: sync-02
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "o2"
          - name: sync-o3
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "o3"
          - name: sync-o4
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "o4"
