apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wow-bootstrap-org1-1
spec:
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      steps:
        - - name: sync-app-of-apps
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "apps-org0"
          - name: sync-admin0
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "admin0"
          - name: sync-tlsca0
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "tlsca0"
          - name: sync-rca0
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "rca0"
