apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wow-sync-org1-1
spec:
  entrypoint: main
  serviceAccountName: workflow
  templates:
    - name: main
      steps:
        - - name: sync-app-of-apps
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "apps-org1"
        - - name: sync-admin1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "admin1"
        - - name: sync-tlsca1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "tlsca1"
          - name: sync-rca1
            templateRef:
              name: argocd-cli
              template: argocd-app-sync
            arguments:
              parameters:
                - name: app
                  value: "rca1"
