caName: tlsca0
domain: org0.com
# MUST conform mspId from configtx.yaml
mspId: Org0MSP
# ReleaseName of deployed "hlf-ca" application
hlfCaReleaseName: tlsca0
# if deploying RCA, orgAdmin = true
# Or otherwise deploying TLSCA, orgAdmin = false
orgAdmin: false
podGC: false
# Defining input parameters, used by step "Register-Member"
items:
  - id: orderer0.org0.com
    type: orderer
    csrHosts: "o0-hlf-ord,orderer0.org0.com,127.0.0.1"
  - id: orderer1.org0.com
    type: orderer
    csrHosts: "o1-hlf-ord,orderer1.org0.com,127.0.0.1"
  - id: orderer2.org0.com
    type: orderer
    csrHosts: "o2-hlf-ord,orderer2.org0.com,127.0.0.1"
  - id: orderer3.org0.com
    type: orderer
    csrHosts: "o3-hlf-ord,orderer3.org0.com,127.0.0.1"
  - id: orderer4.org0.com
    type: orderer
    csrHosts: "o4-hlf-ord,orderer4.org0.com,127.0.0.1"
pvcName: pvc-org0

