{{- if .Values.orderer.enabled }}
# For use by org0 to create genesis block
apiVersion: v1
kind: ConfigMap
metadata:
  name: orgadmin--configtx
  labels:
{{- include "labels.standard" . | nindent 4 }}
data:
  configtx.yaml: |
    Organizations:
      - &Org0MSP
        Name: Org0MSP
        ID: Org0MSP
        MSPDir: /var/hyperledger/crypto-config/Org0MSP/msp
        Policies:
          Readers:
            Type: Signature
            Rule: "OR('Org0MSP.member')"
          Writers:
            Type: Signature
            Rule: "OR('Org0MSP.member')"
          Admins:
            Type: Signature
            Rule: "OR('Org0MSP.admin')"
      - &Org1MSP
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: /var/hyperledger/crypto-config/Org1MSP/msp
        Policies:
          Readers:
            Type: Signature
            Rule: "OR('Org1MSP.member')"
          Writers:
            Type: Signature
            Rule: "OR('Org1MSP.member')"
          Admins:
            Type: Signature
            Rule: "OR('Org1MSP.admin')"
          Endorsement:
            Type: Signature
            Rule: "OR('Org1MSP.member')"
        AnchorPeers:
          - Host: "peer0.org1.net"
            Port: 15443
    Capabilities:
      Channel: &ChannelCapabilities
        V2_0: true
      Orderer: &OrdererCapabilities
        V2_0: true
      Application: &ApplicationCapabilities
        V2_0: true
    Application: &ApplicationDefaults
      Organizations:
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        # Admins:
        #   Type: ImplicitMeta
        #   Rule: "MAJORITY Admins"
        Admins:
          Type: Signature
          Rule: "OR('Org1MSP.admin','Org1MSP.member')"
        LifecycleEndorsement:
          Type: Signature
          Rule: "AND('Org1MSP.member')"
        Endorsement:
          Type: ImplicitMeta
          Rule: "MAJORITY Endorsement"
      Capabilities:
        <<: *ApplicationCapabilities
    Orderer: &OrdererDefaults
      OrdererType: etcdraft
      Addresses:
        - "orderer0.org0.com:15443"
        - "orderer1.org0.com:15443"
        - "orderer2.org0.com:15443"
        - "orderer3.org0.com:15443"
        - "orderer4.org0.com:15443"
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 500
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 2 MB
      MaxChannels: 10
      EtcdRaft:
        Consenters:
          - Host: o0-hlf-ord
            Port: 7050
            ClientTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer0.org0.com/tls-msp/signcerts/cert.pem
            ServerTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer0.org0.com/tls-msp/signcerts/cert.pem
          - Host: o1-hlf-ord
            Port: 7050
            ClientTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer1.org0.com/tls-msp/signcerts/cert.pem
            ServerTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer1.org0.com/tls-msp/signcerts/cert.pem
          - Host: o2-hlf-ord
            Port: 7050
            ClientTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer2.org0.com/tls-msp/signcerts/cert.pem
            ServerTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer2.org0.com/tls-msp/signcerts/cert.pem
          - Host: o3-hlf-ord
            Port: 7050
            ClientTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer3.org0.com/tls-msp/signcerts/cert.pem
            ServerTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer3.org0.com/tls-msp/signcerts/cert.pem
          - Host: o4-hlf-ord
            Port: 7050
            ClientTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer4.org0.com/tls-msp/signcerts/cert.pem
            ServerTLSCert: /var/hyperledger/crypto-config/Org0MSP/orderer4.org0.com/tls-msp/signcerts/cert.pem
        Options:
          TickInterval: 500ms
          ElectionTick: 10
          HeartbeatTick: 1
          MaxInflightBlocks: 5
          SnapshotIntervalSize: 20 MB
      Organizations:
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
    Channel: &ChannelDefaults
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        <<: *ChannelCapabilities
    Profiles:
      OrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
          <<: *OrdererDefaults
          Organizations:
            - *Org0MSP
          Capabilities:
            <<: *OrdererCapabilities
        Consortiums:
          SampleConsortium:
            Organizations:
              - *Org1MSP
      OrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
          <<: *ApplicationDefaults
          Organizations:
            - *Org1MSP
          Capabilities:
            <<: *ApplicationCapabilities
{{- else}}
# For use by org2 or ... to create new org update block; via "neworg" workflow
apiVersion: v1
kind: ConfigMap
metadata:
  name: orgadmin-configtx
  labels:
  {{- include "labels.standard" . | nindent 4 }}
data:
  configtx.yaml: |
    Organizations:
      - &{{ .Values.global.mspId }}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: {{ .Values.global.mspId }}
        # ID to load the MSP definition as
        ID: {{ .Values.global.mspId }}
        MSPDir: /var/hyperledger/crypto-config/{{ .Values.global.mspId }}/msp
        Policies:
          Readers:
            Type: Signature
            Rule: "OR('{{ .Values.global.mspId }}.member')"
          Writers:
            Type: Signature
            Rule: "OR('{{ .Values.global.mspId }}.member')"
          Admins:
            Type: Signature
            Rule: "OR('{{ .Values.global.mspId }}.admin')"
          Endorsement:
            Type: Signature
            Rule: "OR('{{ .Values.global.mspId }}.member')"
        AnchorPeers:
          # AnchorPeers defines the location of peers which can be used
          # for cross org gossip communication.  Note, this value is only
          # encoded in the genesis block in the Application section context
          - Host: {{ .Values.anchorPeer.host }}
            Port: {{ .Values.anchorPeer.port }}
{{- end }}
