apiVersion: v1
kind: ConfigMap
metadata:
  name: orgadmin--cli
  labels:
{{- include "labels.standard" . | nindent 4 }}
data:
  ARGOCD_SERVER: {{ .Values.argocd.url }}
  workflow: "1"  # Only one workflow can run at given time in particular namespace
  template: "5" # Five instance of template can run at a given time in particular namespace
  {{- if .Values.peer.enabled }}
  CORE_PEER_ADDRESS: {{ .Values.peer.config.peerAddress }}
  {{- end }}
  CORE_PEER_ID: "cli"
  CORE_PEER_LOCALMSPID: {{ .Values.global.mspId }}
  CORE_PEER_MSPCONFIGPATH: "{{ .Values.global.workingDir }}/{{ .Values.global.mspId }}/admin/msp"
  CORE_PEER_TLS_ENABLED: "true"
  {{- if .Values.peer.enabled }}
  CORE_PEER_TLS_ROOTCERT_FILE: {{ .Values.peer.config.peerTlsRootcertFile }}
  {{- end }}
  CORE_VM_ENDPOINT: 'unix:///host/var/run/docker.sock'
  FABRIC_CFG_PATH: /var/hyperledger/cli
  FABRIC_LOGGING_SPEC: {{ .Values.global.logging }}
  GOPATH: "/opt/gopath"
  GODEBUG: "netdns=go"
  TZ: {{ .Values.global.TZ }}
  CHANNEL_NAME: "loanapp"
  BIN: /var/hyperledger/bin
  connection.json: |
    {
      "address": "eventstore-hlf-cc:7052",
      "dial_timeout": "10s",
      "tls_required": false,
      "client_auth_required": false,
      "client_key": "-----BEGIN EC PRIVATE KEY----- ... -----END EC PRIVATE KEY-----",
      "client_cert": "-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----",
      "root_cert": "-----BEGIN CERTIFICATE---- ... -----END CERTIFICATE-----"
    }
  metadata.json: |
    {"path":"","type":"external","label":"eventstorev1"}
