apiVersion: v1
kind: Secret
metadata:
  name: crypto-material
type: Opaque
data:
  tlsca_caadmin: {{ $.Values.tlsca_caadmin }}
  tlsca_caadminpw: {{ $.Values.tlsca_caadminpw }}
  rca_caadmin: {{ $.Values.rca_caadmin }}
  rca_caadminpw: {{ $.Values.rca_caadminpw }}
  orgadmin: {{ $.Values.orgadmin }}
  orgadminpw: {{ $.Values.orgadminpw }}
  {{- if $.Values.items }}
  {{- range $.Values.items }}
  {{ .id_unencrypted }}: {{ .secret }}
  {{- end }}
  {{- end }}
---
{{- if .Values.gcpS3Bucket }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-s3-credentials
type: Opaque
data:
  accessKey: {{ $.Values.gcp_storage_accesskey }}
  secretKey: {{ $.Values.gcp_storage_secret }}
{{- end }}
