project: my-project
target: dev-0.2
ns: n2
server: https://kubernetes.default.svc
repoURL: git@github.com:rtang03/fabric-cd.git

apps:
  - path: orgadmin
    rel: admin2
    file: values-admin2.yaml
    secret: secrets.admin2.yaml
  - path: hlf-ca
    rel: tlsca2
    file: values-tlsca2.yaml
    secret: secrets.org2.yaml
  - path: hlf-ca
    rel: rca2
    file: values-rca2.yaml
    secret: secrets.org2.yaml
  - path: hlf-peer
    rel: p0o2
    file: values-p0o2.yaml
  - path: gupload
    rel: g2
    file: values-g2.yaml
  - path: hlf-cc
    rel: eventstore2
    file: values-org2.yaml
  - path: redis
    rel: redis2
    file: values-org2.yaml
  - path: auth-server
    rel: auth-server2
    secret: secrets.org2.yaml
    file: values-org2.yaml
  - path: gw-org
    rel: gw-org2
    secret: secrets.org2.yaml
    file: values-org2.yaml
