project: my-project
target: dev-0.2
ns: n1
server: https://kubernetes.default.svc
repoURL: git@github.com:rtang03/fabric-cd.git

apps:
  - path: redis
    rel: redis1
    file: values-org1.yaml
  - path: auth-server
    rel: auth-server1
    file: values-org1.yaml

