
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: logging
  name: elastic-istio
spec:
  version: 7.6.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      spec:
        automountServiceAccountToken: true
---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: logging
  name: elastic-istio
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elastic-istio
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      automountServiceAccountToken: true
---

apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  namespace: logging
  name: elastic-istio
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elastic-istio
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      automountServiceAccountToken: true
