apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fetch-block
spec:
  # must complete in 1 min (600 seconds)
  activeDeadlineSeconds: 600
  # podGC:
  #   strategy: OnPodCompletion
  serviceAccountName: workflow
  entrypoint: fetch-block-tmpl
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: gcp_dev
  volumes:
    - name: fabricfiles
      persistentVolumeClaim:
        claimName: {{ .Values.pvc }}

  templates:
    - name: fetch-block-tmpl
      steps:
        - - name: fetch
            template: fetch
            arguments:
              parameters:
                - name: x
                  value: "y"
          - name: gupload
            template: gupload
            arguments:
              parameters:
                - name: secretName
                  value: ""

    - name: fetch
{{ toYaml .Values.no_istio | indent 6 }}
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        workingDir: /var/hyperledger
        args:
          - |-
            echo "1"
        volumeMounts:
          - mountPath: /var/hyperledger
            name: fabricfiles
        resources:
          limits:
            cpu: 20m
            memory: 64Mi
    - name: gupload
{{ toYaml .Values.no_istio | indent 6 }}
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        args:
          - |-
            echo "2"
