apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
{{- include "labels.standard" . | nindent 4 }}
data:
  redis-config: |
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy allkeys-lru
