apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "redis.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      initContainers:
        - name: disable-thp
          image: busybox
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          command: ["sh", "-c", "echo never >/host-sys/kernel/mm/transparent_hugepage/enabled"]
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - redis-server
            - "/redis-master/redis.conf"
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "redis.fullname" . }}
            items:
              - key: redis-config
                path: redis.conf
