apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gupload1
  labels:
    app: gupload
    release: "g1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-org2
  labels:
    app: orgadmin
    release: "admin1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-p0o2
  labels:
    app: hlf-peer
    release: "p0o1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
