apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-control.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-request
  selector:
    app: {{ include "ui-control.name" . }}
    release: {{ .Release.Name }}
