apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-org1
  labels:
    app: orgadmin
    release: "admin1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gupload1
  labels:
    app: gupload
    release: "g1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-p0o1
  labels:
    app: hlf-peer
    release: "p0o1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redis1
  labels:
    app: redis
    release: "redis1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
