---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-redis1
  labels:
    app: redis
    release: "redis1"
    namespace: n1
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
