apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dl-create-tlscacert-
spec:
  activeDeadlineSeconds: 300
  # podGC:
  #   strategy: OnPodCompletion
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  serviceAccountName: workflow
  arguments:
    parameters:
      - name: filename
        value: "org0.com-tlscacert.pem"
      - name: key
        value: "tlscacert.pem"
      - name: path
        value: /var/gupload/fileserver/public
      - name: pvc_gupload
        value: "pvc-gupload1"
      - name: secretName
        value: "org0.com-tlscacert"
      - name: url
        value: "https://storage.googleapis.com/fabric-cd-dev/workflow/secrets/n0/org0.com-tlscacert/tlscacert.pem"
  workflowTemplateRef:
    name: download-and-create-secret
