apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: p0o1-gateway
  namespace: n1
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: tls-p0o1
        protocol: HTTPS
      hosts:
        - peer0.org1.net
      tls:
        mode: PASSTHROUGH
---
