apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: p0o2-gateway
  namespace: n2
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      hosts:
        - "peer0.org2.net"
        - "gupload.org2.net"
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: o0-hlf-ord
  namespace: n2
spec:
  hosts:
    - orderer0.org0.com
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: o1-hlf-ord
  namespace: n2
spec:
  hosts:
    - orderer1.org0.com
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: o2-hlf-ord
  namespace: n2
spec:
  hosts:
    - orderer2.org0.com
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: o3-hlf-ord
  namespace: n2
spec:
  hosts:
    - orderer3.org0.com
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: o4-hlf-ord
  namespace: n2
spec:
  hosts:
    - orderer4.org0.com
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: p0o2-hlf-peer
  namespace: n2
spec:
  hosts:
    - peer0.org2.net
    - p0o2-hlf-peer
  gateways:
    -  p0o2-gateway
  tls:
    - match:
        - port: 15443
          sniHosts:
            - peer0.org2.net
        - port: 7051
          sniHosts:
            - p0o2-hlf-peer
      route:
        - destination:
            host: p0o2-hlf-peer.n2.svc.cluster.local
            port:
              number: 7051
    - match:
        - port: 7052
          sniHosts:
            - p0o2-hlf-peer
      route:
        - destination:
            host: p0o1-hlf-peer.n2.svc.cluster.local
            port:
              number: 7052
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eventstore-hlf-cc
  namespace: n2
spec:
  hosts:
    - eventstore-hlf-cc
  http:
    - route:
        - destination:
            host: eventstore-hlf-cc.n2.svc.cluster.local
            port:
              number: 7052
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: g2-gupload
  namespace: n2
spec:
  hosts:
    - gupload.org2.net
  gateways:
    - p0o2-gateway
  tls:
    - match:
        - port: 15443
          sniHosts:
            - gupload.org2.net
      route:
        - destination:
            host: g2-gupload.n2.svc.cluster.local
            port:
              number: 1313

