---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: p0o1-hlf-peer
  namespace: n0
spec:
  hosts:
    - peer0.org1.net
  location: MESH_EXTERNAL
  ports:
    - number: 15443
      name: https
      protocol: TLS
  resolution: NONE

