{{- if eq .Values.clusterscope false }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: simple-echo
spec:
  activeDeadlineSeconds: 3600
  # podGC:
  #   strategy: OnPodCompletion
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  serviceAccountName: workflow
  entrypoint: echo

  templates:
    # Retrieve file via http
    - name: echo
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: message
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        args:
          - |-
            echo "SIMPLE ECHO"
            echo {{ .Values.alias.input_message }}
  {{- end }}
