{{- if eq .Values.clusterscope false }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: channel-operations
spec:
  activeDeadlineSeconds: 3600
  # podGC:
  #   strategy: OnPodCompletion
  serviceAccountName: workflow

  volumes:
    # binaries: peer, etc.
    - name: fabricfiles
      persistentVolumeClaim:
        claimName: {{ .Values.pvc_fabricfiles }}
    - name: setup-script
      configMap:
        name: "orgadmin--setupsh"
        defaultMode: 0777

  templates:
    - name: fetch-block-tmpl
      container:

{{- end }}
