pvc_fabricfiles: pvc-org1
pvc_gupload: pvc-gupload1

hostAlias:
  - hostnames:
      - orderer0.org0.com
      - peer0.org1.net
    ip: 35.202.107.80
  - hostnames:
      - gupload.org2.net
    ip: 35.202.107.80

ordererUrl: orderer0.org0.com

address:
  url: gupload.org2.net
  port: 15443
