apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
{{- include "labels.standard" . | nindent 4 }}
data:
  CLIENT_APPLICATION_NAME: "root_client"
  JWT_EXP_IN_SECOND: {{ .Values.config.jwtExpInSecond | quote }}
  LOG_LEVEL: {{ .Values.global.logging | quote }}
  LOG_TARGET: "console"
  ORG_ADMIN_EMAIL: {{ .Values.config.orgadminEmail | quote }}
  PORT: {{ .Values.config.port | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REFRESH_TOKEN_EXP_IN_SEC: {{ .Values.config.refreshTokenExpInSec | quote }}
  TYPEORM_DATABASE: "auth_db"
  TYPEORM_HOST: {{ .Values.config.postgresHost | quote }}
  TYPEORM_PORT: {{ .Values.config.postgresPort | quote }}
  TZ: {{ .Values.global.TZ  | quote }}
