apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "auth-server.name" . }}
      release: {{ .Release.Name }}
  template:
    spec:
      containers:
        - name: main
          image: ho1ho/auth-server:0.7.0
          workingDir: /var
          command:
            - sh
            - -c
            - |
