apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  hosts:
  - {{ include "auth-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        host: {{ include "auth-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
