{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hlf-operator.fullname" . }}--{{ .Values.createSecret.name }}
data:
  .dockerconfigjson: {{ .Values.dockerConfig }}
{{ end }}
