apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.rel }}
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.path }}
    helm:
      releaseName: {{ .Values.rel }}
      valueFiles:
        - {{ .Values.file | quote }}
        - "secrets.yaml"
      version: v3
  destination:
    server: {{ .Values.server }}
    namespace: {{ .Values.ns }}
