apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.rel }}
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.target }}
    path: {{ .Values.path }}
    helm:
      releaseName: {{ .Values.rel }}
      valueFiles:
        - {{ .Values.file }}
        {{- if .Values.secret }}
        - {{ .Values.secret }}
        {{- end }}
  destination:
    server: {{ .Values.server }}
    {{- if eq .Values.clusterscope false }}
    namespace: {{ .Values.ns }}
    {{- end }}
