configs:
  secret:
    extra:
      # example credential file of service-account of GCP Cloud KMS, with "encrypt/decrypt" access.
      kms-service-account: |
        {
          "type": "service_account",
          "project_id": "fdi-cd",
          "private_key_id": "348b558665fec63dfdecf57f23b3f4cff5e81bb2",
          "private_key": "------INSERT YOUR PRIVATE KEY-----",
          "client_email": "kms-default-service-account@fdi-cd.iam.gserviceaccount.com",
          "client_id": "107114143009673412676",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kms-default-service-account%40fdi-cd.iam.gserviceaccount.com"
        }
