# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
global:
  image:
    repository: "ghcr.io/rtang03/argocd"
    tag: "1.7.7-rel.1"
    imagePullPolicy: Always
  securityContext:
    fsGroup: 2000

repoServer:
  logLevel: info
  volumes:
    - name: "gcp-service-account"
      secret:
        secretName: "argocd-secret"
        items:
          - key: "kms-service-account"
            path: "kms-service-account.json"
        defaultMode: 0600
  volumeMounts:
    - name: "gcp-service-account"
      mountPath: "/app/config/gcp"
