# https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd
global:
  image:
    repository: "ghcr.io/rtang03/argocd"
    tag: "1.7.7-rel.1"
    imagePullPolicy: IfNotPresent
  securityContext:
    fsGroup: 2000

#controller:
#  podAnnotations:
#    sidecar.istio.io/inject: "false"

repoServer:
  logLevel: info
  volumes:
    - name: "gcp-service-account"
      secret:
        secretName: "argocd-secret"
        items:
          - key: "kms-service-account"
            path: "kms-service-account.json"
        defaultMode: 0600
  volumeMounts:
    - name: "gcp-service-account"
      mountPath: "/app/config/gcp"

#dex:
#  podAnnotations:
#    sidecar.istio.io/inject: "false"

#redis:
#  podAnnotations:
#    sidecar.istio.io/inject: "false"

server:
  extraArgs:
    - --insecure
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "false"
    sidecar.istio.io/logLevel: "info"
  config:
    # https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#helm-chart-repositories
    # need to add non standard helm chart for istio, in order for argocd to work
    helm.repositories: |
      - url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
        name: istio.io
    repositories: |
      - type: helm
        url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
        name: istio.io
