apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-cli
spec:
  activeDeadlineSeconds: 300
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  serviceAccountName: workflow
  entrypoint: argocd-app-sync

  templates:
    # Delete Secret resource
    - name: argocd-app-sync
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: app
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        args:
          - |-
            echo "argoServer: $ARGOCD_SERVER"
            echo "argoAuthToken: $ARGOCD_AUTH_TOKEN"
            curl -sSL -o /usr/local/bin/argocd https://${ARGOCD_SERVER}/download/argocd-linux-amd64
            # argocd app sync admin1
        env:
          - name: ARGOCD_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: argocd-cli-jwt
                key: jwt
        envFrom:
          - configMapRef:
              name: orgadmin--cli
