{{- if .Values.createChannel.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-channel
spec:
  activeDeadlineSeconds: 300
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600     # Time to live after workflow fails
  serviceAccountName: workflow
  entrypoint: main

  templates:
    - name: main
{{ toYaml .Values.no_istio | indent 6 }}
      {{- if .Values.hostAlias }}
      hostAliases:
      {{- range .Values.hostAlias }}
        - hostnames:
            {{- range .hostnames }}
            - {{ . }}
            {{- end }}
          ip: {{ .ip }}
      {{- end }}
      {{- end }}
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.pvc_fabricfiles }}
        - name: setup-script
          configMap:
            name: "orgadmin--setupsh"
            defaultMode: 0755
        - name: core-yaml
          configMap:
            name: core-yaml
        - name: org0-tlscacert
          secret:
            secretName: org0.com-tlscacert
        - name: org1-tlscacert
          secret:
            secretName: org0.net-tlscacert
      container:
        inputs:
          parameters:
            - name: channelname
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        workingDir: /var/hyperledger
        args:
          - |-
            CHANNEL_NAME={{ .Values.alias.input_channelname | quote }}
            FABRIC_CFG_PATH=/etc/hyperledger
            ORDERER_CA=/tmp/org0.com-tlscacert.pem
            CORE_PEER_TLS_ROOTCERT_FILE=/tmp/org1.net-tlscacert.pem
            . /script/setup.sh
            apk update
            apk upgrade
            apk --no-cache add libc6-compat libstdc++ tzdata
            ./bin/peer version
            printHeader "Create Channel"
            echo "Fetch block to see if channel has already been created..."
            set -x
            ./bin/peer channel fetch 0 -c $CHANNEL_NAME --tls --cafile $ORDERER_CA -o $ORDERER_URL /tmp/$CHANNEL_NAME.block
            set +x
            if [ -f "/tmp/$CHANNEL_NAME.block" ]
            then
              echo "Channel $CHANNEL_NAME is already created. create-channel skipped" | tee /tmp/createchannel.log
            else
              echo "Creating channel $CHANNEL_NAME"
              set -x
              ./bin/peer channel create -o $ORDERER_URL -c $CHANNEL_NAME -f /tmp/channel.tx --outputBlock /tmp/$CHANNEL_NAME.block --tls --cafile $ORDERER_CA >& /tmp/createchannel.log
              res=$?
              set +x
              cat /tmp/createchannel.log
              printMessage "generate $CHANNEL_NAME.block" $res
            fi
        env:
          - name: ORDERER_URL
            value: {{ .Values.ordererUrl }}
        envFrom:
          - configMapRef:
              name: orgadmin--cli
        volumeMounts:
          - mountPath: /var/hyperledger
            name: fabricfiles
          - name: setup-script
            mountPath: /script/setup.sh
            subPath: setup.sh
          - mountPath: /etc/hyperledger
            name: core-yaml
          - mountPath: /tmp/org0.com-tlscacert.pem
            name: org0-tlscacert
          - mountPath: /tmp/org1.net-tlscacert.pem
            name: org1-tlscacert
      outputs:
        parameters:
          - name: channel_block_s3_path
            value: workflow/{{ .Values.alias.workflow_name }}/{{ .Values.mspId | lower }}/create-channel/{{ .Values.alias.input_channelname }}.block
        artifacts:
          - name: channel-block
            path: /tmp/
            archive:
              none: {}
            s3:
              key: workflow/{{ .Values.alias.workflow_name }}/{{ .Values.mspId | lower }}/create-channel/
              {{- with .Values.s3 }}
{{ toYaml . | indent 14 }}
              {{- end }}
{{- end }}
