apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: curl-event
spec:
  activeDeadlineSeconds: 60
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterSuccess: 3600
    secondsAfterFailure: 3600
  serviceAccountName: workflow

  templates:
    - name: curl-tmpl
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: url
          - name: message
      {{- if .Values.hostAlias }}
      hostAliases:
      {{- range .Values.hostAlias }}
        - hostnames:
            {{- range .hostnames }}
            - {{ . }}
            {{- end }}
          ip: {{ .ip }}
      {{- end }}
      {{- end }}
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        args:
          - |-
            apk update
            apk upgrade
            apk --no-cache add libc6-compat libstdc++ curl
            echo "url {{ .Values.alias.input_url }}"
            echo "data: {{ .Values.alias.input_message }}"
            set -x
            curl {{ .Values.alias.input_url }} -H "Authorization: $ARGO_TOKEN" -d "{{ .Values.alias.input_message }}"
            res=$?
            echo "response code: $res"
            exit $res
        envFrom:
          - secretRef:
              name: org1.net-guest-token
