{{- if .Values.createChannel.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-channel
spec:
  activeDeadlineSeconds: 300
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterSuccess: 3600
    secondsAfterFailure: 3600
  serviceAccountName: workflow
  entrypoint: main

  templates:
    - name: main
{{ toYaml .Values.no_istio | indent 6 }}
      inputs:
        parameters:
          - name: channelname
          - name: update_channel_env
      {{- if .Values.hostAlias }}
      hostAliases:
      {{- range .Values.hostAlias }}
        - hostnames:
            {{- range .hostnames }}
            - {{ . }}
            {{- end }}
          ip: {{ .ip }}
      {{- end }}
      {{- end }}
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.pvc_fabricfiles }}
        - name: setup-script
          configMap:
            name: "orgadmin--setupsh"
            defaultMode: 0755
        - name: core-yaml
          configMap:
            name: core-yaml
        - name: org0-tlscacert
          secret:
            secretName: org0.com-tlscacert
        - name: org1-tlscacert
          secret:
            secretName: org1.net-tlscacert
      container:
        image: library/alpine:3.12.0
        command: ["sh", "-c"]
        workingDir: /var/hyperledger
        args:
          - |-
            ENVELOPE="{{ .Values.alias.input_update_channel_env }}"
            CHANNEL_NAME={{ .Values.alias.input_channelname | quote }}
            ORDERER_URL={{ .Values.ordererUrl }}
            FABRIC_CFG_PATH=/etc/hyperledger
            ORDERER_CA=/tmp/org0.com-tlscacert.pem
            CORE_PEER_TLS_ROOTCERT_FILE=/tmp/org1.net-tlscacert.pem
            echo "CHANNEL_NAME: $CHANNEL_NAME"
            echo "ORDERER_URL: $ORDERER_URL"
            . /script/setup.sh
            apk update
            apk upgrade
            apk --no-cache add libc6-compat libstdc++ tzdata
            ./bin/peer version
            ### check config.json exists
            if [ -f "/tmp/$ENVELOPE" ]
            then
              # echo "config_update_in_envelope.pb exists"
              echo "$ENVELOPE exists"
            else
              printMessage "find config_update_in_envelope.pb" 1
            fi
            printHeader "Update channel"
            set -x
            ./bin/peer channel update -f /tmp/$ENVELOPE -c $CHANNEL_NAME -o $ORDERER_URL --tls --cafile $ORDERER_CA >& $TMP/updatechannel.log
            res=$?
            set +x
            cat $TMP/updatechannel.log
            printMessage "update channel" $res
        envFrom:
          - configMapRef:
              name: orgadmin--cli
        volumeMounts:
          - mountPath: /var/hyperledger
            name: fabricfiles
          - name: setup-script
            mountPath: /script/setup.sh
            subPath: setup.sh
          - mountPath: /etc/hyperledger
            name: core-yaml
          - mountPath: /tmp/org0.com-tlscacert.pem
            name: org0-tlscacert
            subPath: tlscacert.pem
          - mountPath: /tmp/org1.net-tlscacert.pem
            name: org1-tlscacert
            subPath: tlscacert.pem
      outputs:
        artifacts:
          - name: update-channel
            path: /tmp/
            archive:
              none: {}
            s3:
              key: workflow/{{ .Values.alias.workflow_name }}/{{ .Values.mspId | lower }}/update-channel/
              {{- with .Values.s3 }}
{{ toYaml . | indent 14 }}
              {{- end }}
{{- end }}
