{{- if .Values.externalDatabase.type }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-ca.fullname" . }}--db
  labels:
{{- include "labels.standard" . | nindent 4 }}
type: Opaque
data:
  db_username: {{ $.Values.externalDatabase.username }}
  db_password: {{ $.Values.externalDatabase.password }}
{{- end }}
