apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlf-cc.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hlf-cc.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "50m"
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          name: chaincode
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7052
          env:
            - name: CHAINCODE_CCID
              value: {{ .Values.ccid | quote}}
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
            - name: TZ
              value: {{ .Values.global.TZ | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
