apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlf-cc.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hlf-cc.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "50m"
        sidecar.istio.io/proxyCPULimit: "50m"
        # trace|debug|info|warning|error|critical|off
        sidecar.istio.io/logLevel: "info"
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      initContainers:
        - name: check
          image: library/busybox:1.32
          command: ["sh", "-c"]
          args:
            - |-
              if [ $CHAINCODE_CCID = "" ]; then
                echo "🚫  CHAINCODE_CCID is empty"
                exit 1
              fi
          envFrom:
            - configMapRef:
                name: "chaincode-ccid"
      containers:
        - image: {{ .Values.image }}
          name: chaincode
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7052
          env:
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
            - name: TZ
              value: {{ .Values.global.TZ | quote }}
          envFrom:
            - configMapRef:
                name: "chaincode-ccid"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
