apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-consumer
spec:
  event:
    selector: payload.message != "" && discriminator == "my-discriminator"
    # selector: payload.message != "" && metadata["x-argo"] == ["true"] && discriminator == "my-discriminator"
  submit:
    workflowTemplateRef:
      name: simple-echo
    arguments:
      parameters:
        - name: message
          valueFrom:
            event: payload.message
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-pull-tlscacert
spec:
  event:
    selector: payload.filename != "" && payload.secretname != "" && payload.url != "" && discriminator == "pull-tlscacert"
  submit:
    workflowTemplateRef:
      name: download-and-create-secret
    arguments:
      parameters:
        - name: filename
          valueFrom:
            event: payload.filename
        - name: key
          value: "tlscacert.pem"
        - name: path
          value: /var/gupload/fileserver
        # TODO: IMPORTANT NOTE: currently, there is only one Argo Server for org0/org1. Later phase,
        # we will split, so that each new org will have its own Argo-Server, the below mounted volume
        # need modify
        - name: pvc_gupload
          value: "pvc-gupload1"
        - name: secretName
          valueFrom:
            event: payload.secretname
        - name: url
          valueFrom:
            event: payload.url
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-fetch-block
spec:
  event:
    selector: payload.address != "" && discriminator == "fetch-block"
  submit:
    workflowTemplateRef:
      name: fetch-block-tmpl
    arguments:
      parameters:
        - name: address
          valueFrom:
            event: payload.address
