apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orgadmin
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - list
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orgadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orgadmin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orgadmin
subjects:
  - kind: ServiceAccount
    name: orgadmin
