apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-org
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workfloweventbindings
    verbs:
      - list
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtemplates
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-org
subjects:
  - kind: ServiceAccount
    name: guest
