{{- if .Values.fetchSend.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hlf-operator.fullname" . }}--fetch
  labels:
{{- include "labels.standard" . | nindent 4 }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      {{- if .Values.fetchSend.hostAlias }}
      hostAliases:
        {{- range .Values.fetchSend.hostAlias }}
        - hostnames:
            {{- range .hostnames }}
            - {{ . }}
          {{- end }}
          ip: {{ .ip }}
      {{- end }}
      {{- end }}
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: {{ .Values.fetchSend.orgadmin.pvcName }}
        - name: upload
          persistentVolumeClaim:
            claimName: {{ .Values.fetchSend.gupload.pvcName }}
        - name: setup-script
          configMap:
            name: {{ .Values.global.config.setupsh }}
            defaultMode: 0777
        - name: core-yaml
          configMap:
            name: {{ .Values.global.config.coreyaml }}
        {{- range .Values.fetchSend.secret }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secret }}
        {{- end }}
      containers:
        - name: job
          image: {{ .Values.global.guploadImage | quote }}
          command: ["sh", "-c"]
          workingDir: /var/hyperledger
          args:
            - |-
              . /script/setup.sh
              apk update
              apk upgrade
              apk --no-cache add libc6-compat libstdc++ jq
              $BIN/peer version
              ### Fetch channel config and turn into config.json
              printHeader "Fetch channel config"
              export TMP={{ .Values.global.workingDir }}/uploaded/tmp/{{include "hlf-operator.fullname" .}}
              set -x
              rm -r $TMP
              mkdir -p $TMP
              $BIN/peer channel fetch config $TMP/config_block.pb -o ${ORDERER_URL} -c ${CHANNEL_NAME} --tls --cafile ${ORDERER_CA} >& $TMP/fetchconfig.log
              res=$?
              set +x
              printMessage "fetch channel config: config_block.pb" $res
              cat $TMP/fetchconfig.log
              printHeader "Decoding config block to JSON and isolating config"
              set -x
              $BIN/configtxlator proto_decode --input $TMP/config_block.pb --type common.Block | jq .data.data[0].payload.data.config > $TMP/config.json
              res=$?
              set +x
              printMessage "decode block and extract channel config: config.json" $res
              ### Gupload
              printHeader "Gupload to remote server"
              set -x
              /var/gupload/gupload upload --cacert /var/gupload/cert/tlscacert.pem --public=false --infile $TMP/config.json --outfile {{ .Values.fetchSend.gupload.uploadedFilename }} --address "{{ .Values.fetchSend.address.url }}:{{ .Values.fetchSend.address.port }}"
              res=$?
              set +x
              printMessage "gupload to {{ .Values.fetchSend.address.url }}:{{ .Values.fetchSend.address.port }}" $res
          envFrom:
            # common configMap
            - configMapRef:
                name: {{ include "hlf-operator.fullname" . }}--cli
          volumeMounts:
            # this mount will share the configtxlator binary
            - mountPath: /var/hyperledger
              name: fabricfiles
            # this job will also mount the gupload pvc, under /var/hyperledger/uploaded
            - mountPath: {{ .Values.global.workingDir }}/uploaded
              name: upload
            # this will enable "peer" cli to run
            - mountPath: /etc/hyperledger
              name: core-yaml
            - name: setup-script
              mountPath: /script/setup.sh
              subPath: setup.sh
            {{- range .Values.fetchSend.secret }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
{{- end }}
