pvc_fabricfiles: pvc-org1
pvc_gupload: pvc-gupload1

clusterscope: false

guploadImage: ghcr.io/rtang03/gupload:0.1.6

ordererUrl: orderer0.org0.com

argocdServerUrl: argocd.server

createChannel:
  enabled: false

updateAnchorPeer:
  enabled: false

neworg:
  enabled: false

#hostAlias:
#  - hostnames:
#      - orderer0.org0.com
#      - peer0.org1.net
#    ip: 35.202.107.80
#  - hostnames:
#      - gupload.org2.net
#    ip: 35.202.107.80

s3:
  endpoint: storage.googleapis.com
  bucket: fabric-cd-dev
  accessKeySecret:
    name: gcp-s3-credentials
    key: accessKey
  secretKeySecret:
    name: gcp-s3-credentials
    key: secretKey

alias:
  # general
  workflow_name: "{{workflow.name}}"
  input_cacert: "{{inputs.parameters.cacert}}"
  # used by simple-echo
  input_message: "{{inputs.parameters.message}}"
  # used by dl-create-secret
  input_pvc_gupload: "{{inputs.parameters.pvc_gupload}}"
  input_url: "{{inputs.parameters.url}}"
  input_secretName: "{{inputs.parameters.secretName}}"
  input_filename: "{{inputs.parameters.filename}}"
  input_path: "{{inputs.parameters.path}}"
  input_key: "{{inputs.parameters.key}}"
  key1: "{{inputs.parameters.key1}}"
  path1: "{{inputs.parameters.path1}}"
  value1: "{{inputs.parameters.value1}}"
  key2: "{{inputs.parameters.key2}}"
  path2: "{{inputs.parameters.path2}}"
  value2: "{{inputs.parameters.value2}}"
  output_value1: "{{steps.retrieve.outputs.parameters.value1}}"
  # used by gupload
  input_infile: "{{inputs.parameters.infile}}"
  input_outfile: "{{inputs.parameters.outfile}}"
  # used by argocd-cli
  input_app: "{{inputs.parameters.app}}"
  # used by create-channel
  input_channelname: "{{inputs.parameters.channelname}}"

no_istio:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
