global:
  TZ: Asia/Hong_Kong
  mspId: Org0MSP
  workingDir: /home/app
  logging: info

image:
  repository: ghcr.io/rtang03/gw-org1
  tag: 0.7.1
  pullPolicy: IfNotPresent

hostAlias:
  - hostnames:
      - orderer0.org0.com
      - orderer1.org0.com
      - orderer2.org0.com
      - orderer3.org0.com
      - orderer4.org0.com
      - peer0.org1.net
    ip: 35.202.107.80
  - hostnames:
      - peer0.org2.net
    ip: 35.202.107.80

persistence:
  ### Default
  # annotations: {}
  ### Default
  # accessMode: ReadWriteOnce
  ### Default
  # enabled: true
  pvcName: pvc-p0o1

config:
  orgAdmin: admin-org1.net
  orgAdminSecret: admin-org1.netPW
  gatewayHost: gw-org1
  redisHost: redis01
  packageName: gw-org1
  authServerUri: auth-server1:8080

connection:
  registrar:
    enrollId: rca-org1-admin
    enrollSecret: rca-org1-adminPW
  ca:
    name: rca1-hlf-ca
    url: rca1-hlf-ca:7054
#    tlscacerts:
#      path: /var/artifacts/crypto-config/Org1MSP/msp/tlscacerts/tls-ca-cert.pem
  channelName: loanapp
  ordererCa: /tmp/org0.com-tlscacert.pem
  peers:
    - name: peer0
      healthz: p0o1-hlf-peer:9443
      url: p0o1-hlf-peer:7051
      eventUrl: p0o1-hlf-peer:7053
      grpcOptions:
        nameOverride: p0o1-hlf-peer
      tlscacert: /tmp/org1.net-tlscacert.pem
  orderers:
    - name: orderer0
      url: orderer0.org0.com:15443
      grpcOptions:
        nameOverride: orderer0.org0.com
    - name: orderer1
      url: orderer1.org0.com:15443
      grpcOptions:
        nameOverride: orderer1.org0.com
    - name: orderer2
      url: orderer2.org0.com:15443
      grpcOptions:
        nameOverride: orderer2.org0.com
    - name: orderer3
      url: orderer3.org0.com:15443
      grpcOptions:
        nameOverride: orderer3.org0.com
    - name: orderer4
      url: orderer4.org0.com:15443
      grpcOptions:
        nameOverride: orderer4.org0.com

secrets:
  - name: org0-tlscacert
    secretName: org0.com-tlscacert
    mountPath: /tmp/org0.com-tlscacert.pem
    subPath: tlscacert.pem
  - name: org1-tlscacert
    secretName: org1.net-tlscacert
    mountPath: /tmp/org1.net-tlscacert.pem
    subPath: tlscacert.pem
  - name: admin-cert
    secretName: peer0.org1.net-admincert
    mountPath: /tmp/org1.net-admin-cert.pem
    subPath: org1.net-admin-cert.pem
  - name: admin-key
    secretName: peer0.org1.net-adminkey
    mountPath: /tmp/org1.net-admin-key.pem
    subPath: org1.net-admin-key.pem

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
