apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      protocol: TCP
      name: tls-request
    - port: {{ .Values.service.portEvent }}
      targetPort: 7053
      protocol: TCP
      name: tls-event
    - port: 9443
      targetPort: 9443
      name: http-metrics
      protocol: TCP
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
