apiVersion: v1
kind: Service
metadata:
  name: {{ include "gw-org.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: http-request
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http-queryhandler
  selector:
    app: {{ include "gw-org.name" . }}
    release: {{ .Release.Name }}
