apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "gw-org.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  hosts:
    - gw.{{ .Values.global.domain }}
    - {{ include "gw-org.fullname" . }}
  gateways:
    - {{ .Values.global.istiogateway }}
  http:
    - route:
        - destination:
            host: {{ include "gw-org.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 4001
