apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dl-create-tlscacert-
spec:
  activeDeadlineSeconds: 300
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterSuccess: 3600
    secondsAfterFailure: 3600
  entrypoint: main
  serviceAccountName: workflow

  templates:
    - name: main
      steps:
        # STEP 1: send org1.net-tlscacert.pem to to n2 /var/gupload/fileserver; and create secret
        - - name: load-org1tlscacert
            arguments:
              parameters:
                - name: filename
                  value: "org1.net-tlscacert.pem"
                - name: key
                  value: "tlscacert.pem"
                - name: path
                  value: /var/gupload/fileserver
                - name: pvc_gupload
                  value: "pvc-gupload2"
                - name: secretName
                  value: "org1.net-tlscacert"
                - name: url
                  value: "https://storage.googleapis.com/fabric-cd-dev/workflow/secrets/n1/org1.net-tlscacert/tlscacert.pem"
            templateRef:
              name: download-and-create-secret
              template: main

        # STEP 2: send org2.net-tlscacert.pem to to n2 /var/gupload/fileserver; and create secret
          - name: load-org2tlscacert
            arguments:
              parameters:
                - name: filename
                  value: "org2.net-tlscacert.pem"
                - name: key
                  value: "tlscacert.pem"
                - name: path
                  value: /var/gupload/fileserver
                - name: pvc_gupload
                  value: "pvc-gupload2"
                - name: secretName
                  value: "org2.net-tlscacert"
                - name: url
                  value: "https://storage.googleapis.com/fabric-cd-dev/workflow/secrets/n2/org2.net-tlscacert/tlscacert.pem"
            templateRef:
              name: download-and-create-secret
              template: main

        # STEP 3: send org0.com-tlscacert.pem to to n2 /var/gupload/fileserver; and create secret
          - name: load-org0tlscacert
            arguments:
              parameters:
                - name: filename
                  value: "org0.com-tlscacert.pem"
                - name: key
                  value: "tlscacert.pem"
                - name: path
                  value: /var/gupload/fileserver
                - name: pvc_gupload
                  value: "pvc-gupload2"
                - name: secretName
                  value: "org0.com-tlscacert"
                - name: url
                  value: "https://storage.googleapis.com/fabric-cd-dev/workflow/secrets/n0/org0.com-tlscacert/tlscacert.pem"
            templateRef:
              name: download-and-create-secret
              template: main
