# pvc for current namespace attached to orgAdmin
pvc: pvc-org1
bucket: fabric-cd-dev
mspId: Org1MSP

items:
  - secretName: test-peer0.org1.net-cert
    isTls: false
    key1: cert.pem
    path1: Org1MSP/peer0.org1.net/msp/signcerts/cert.pem
  - secretName: test-peer0.org1.net-key
    isTls: false
    key1: key.pem
    path1: Org1MSP/peer0.org1.net/msp/keystore/key.pem
  - secretName: test-peer0.org1.net-tls
    isTls: true
    key1: cert.pem
    path1: Org1MSP/peer0.org1.net/tls-msp/signcerts/cert.pem
    key2: key.pem
    path2: Org1MSP/peer0.org1.net/tls-msp/keystore/key.pem

## DON'T MODIFY ALIAS
itemAlias:
  item: "{{item}}"
  secretName: "{{item.secretName}}"
  key1: "{{item.key1}}"
  path1: "{{item.path1}}"
  value1: "{{item.value1}}"
  key2: "{{item.key2}}"
  path2: "{{item.path2}}"
  value2: "{{item.value2}}"
  isTls: "{{item.isTls}}"
  getOutput: "{{steps.get-files.outputs.parameters}}"
  getOutputSecretName: "{{steps.get-files.outputs.parameters.secretName}}"

inputAlias:
  secretName: "{{inputs.parameters.secretName}}"
  isTls: "{{inputs.parameters.isTls}}"
  key1: "{{inputs.parameters.key1}}"
  path1: "{{inputs.parameters.path1}}"
  value1: "{{inputs.parameters.value1}}"
  key2: "{{inputs.parameters.key2}}"
  path2: "{{inputs.parameters.path2}}"
  value2: "{{inputs.parameters.value2}}"
