# pvc for current namespace attached to orgAdmin
pvc: pvc-org2
mspId: Org2MSP
bucket: fabric-cd-dev

items:
  ######### 1. secret: key
  - secretName: peer0.org2.net-cert
    isTls: false
    key1: cert.pem
    path1: Org2MSP/peer0.org2.net/msp/signcerts/cert.pem
  ######### 2. secret: key
  - secretName: peer0.org2.net-key
    isTls: false
    key1: key.pem
    path1: Org2MSP/peer0.org2.net/msp/keystore/key.pem
  ######### 3. secret: CA cert
  - secretName: peer0.org2.net-cacert
    isTls: false
    key1: cacert.pem
    path1: Org2MSP/peer0.org2.net/msp/cacerts/rca2-hlf-ca-7054.pem
  ######### 4. secret: tls cert and key
  - secretName: peer0.org2.net-tls
    isTls: true
    key1: tls.crt
    path1: Org2MSP/peer0.org2.net/tls-msp/signcerts/cert.pem
    key2: tls.key
    path2: Org2MSP/peer0.org2.net/tls-msp/keystore/key.pem
  ######### 5. secret: tls root CA cert
  - secretName: peer0.org2.net-tlsrootcert
    isTls: false
    key1: tlscacert.pem
    path1: Org2MSP/peer0.org2.net/tls-msp/tlscacerts/tls-tlsca2-hlf-ca-7054.pem
  ######### 6. create secret for org2.net-admin-cert.pem
  - secretName: peer0.org2.net-admincert
    isTls: false
    key1: org2.net-admin-cert.pem
    path1: Org2MSP/admin/msp/admincerts/org2.net-admin-cert.pem
  ######### 7. create secret for org2.net-admin-key.pem
  - secretName: peer0.org2.net-adminkey
    isTls: false
    key1: org2.net-admin-key.pem
    path1: Org2MSP/admin/msp/keystore/key.pem
  ######### 8. Create secret for tls for tlsca, used by ingress controller
  - secretName: tlsca2-tls
    isTls: true
    key1: tls.crt
    path1: Org2MSP/tls/server/ca-cert.pem
    key2: tls.key
    path2: Org2MSP/tls/server/msp/keystore/key.pem
  ######### 9. Create secret for tls for rca, used by ingress controller
  - secretName: rca2-tls
    isTls: true
    key1: tls.crt
    path1: Org2MSP/ca/server/ca-cert.pem
    key2: tls.key
    path2: Org2MSP/ca/server/msp/keystore/key.pem
