# pvc for current namespace attached to orgAdmin
pvc: pvc-org1
mspId: Org1MSP
bucket: fabric-cd-dev

items:
  - secretName: istio1-tls
    isTls: true
    key1: tls.crt
    path1: Org1MSP/tls/server/ca-cert.pem
    key2: tls.key
    path2: Org1MSP/tls/server/msp/keystore/key.pem
