# pvc for current namespace attached to orgAdmin
pvc: pvc-org1
mspId: Org1MSP
bucket: fabric-cd-dev

items:
  ######### 1. secret: key
  - secretName: peer0.org1.net-cert
    isTls: false
    key1: cert.pem
    path1: Org1MSP/peer0.org1.net/msp/signcerts/cert.pem
  ######### 2. secret: key
  - secretName: peer0.org1.net-key
    isTls: false
    key1: key.pem
    path1: Org1MSP/peer0.org1.net/msp/keystore/key.pem
  ######### 3. secret: CA cert
  - secretName: peer0.org1.net-cacert
    isTls: false
    key1: cacert.pem
    path1: Org1MSP/peer0.org1.net/msp/cacerts/rca1-hlf-ca-7054.pem
  ######### 4. secret: tls cert and key
  - secretName: peer0.org1.net-tls
    isTls: true
    key1: tls.crt
    path1: Org1MSP/peer0.org1.net/tls-msp/signcerts/cert.pem
    key2: tls.key
    path2: Org1MSP/peer0.org1.net/tls-msp/keystore/key.pem
  ######### 5. secret: tls root CA cert
  - secretName: peer0.org1.net-tlsrootcert
    isTls: false
    key1: tlscacert.pem
    path1: Org1MSP/peer0.org1.net/tls-msp/tlscacerts/tls-tlsca1-hlf-ca-7054.pem
  ######### 6. create secret for org1.net-admin-cert.pem
  - secretName: peer0.org1.net-admincert
    isTls: false
    key1: org1.net-admin-cert.pem
    path1: Org1MSP/admin/msp/admincerts/org1.net-admin-cert.pem
  ######### 7. create secret for org1.net-admin-key.pem
  - secretName: peer0.org1.net-adminkey
    isTls: false
    key1: org1.net-admin-key.pem
    path1: Org1MSP/admin/msp/keystore/key.pem
  ######### 8. create secret org1.net-cacert.pem for Org0
  - secretName: org1.net-cacert
    isTls: false
    key1: org1.net-ca-cert.pem
    path1: Org1MSP/msp/cacerts/org1.net-ca-cert.pem
  ######## 9. create secret org1.net-admincert for Org0
  - secretName: org1.net-admincert
    isTls: false
    key1: org1.net-admin-cert.pem
    path1: Org1MSP/msp/admincerts/org1.net-admin-cert.pem
  ######## 10. create secret org1.net-tlscacert.pem for Org0
  - secretName: org1.net-tlscacert
    isTls: false
    key1: tlscacert.pem
    path1: Org1MSP/msp/tlscacerts/tls-ca-cert.pem
  ######### 11. Create secret for tls for tlsca, used by ingress controller
  - secretName: tlsca1-tls
    isTls: true
    key1: tls.crt
    path1: Org1MSP/tls/server/ca-cert.pem
    key2: tls.key
    path2: Org1MSP/tls/server/msp/keystore/key.pem
  ######### 12. Create secret for tls for rca, used by ingress controller
  - secretName: rca1-tls
    isTls: true
    key1: tls.crt
    path1: Org1MSP/ca/server/ca-cert.pem
    key2: tls.key
    path2: Org1MSP/ca/server/msp/keystore/key.pem
